### Test Google Sign In
POST http://143.198.54.56:3000/authentication/google
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
}


### Test Company Profile Creation
POST http://143.198.54.56:8081/api/company-profile
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="company-profile"
Content-Type: application/json

{
    "name": "Darik Coffee",
    "taxIdentificationNumber": "123456789", 
    "businessTypeId": "2ff6f208-48c6-47d9-81b7-7427ff77e8a2",
    "industryTypeId": "a2fc821a-9378-433f-9506-a57066d6728c",
    "countryOfIncorporation": "United States",
    "address": "123 Innovation Drive, Silicon Valley, CA",
    "phone": "+1-800-555-1234",
    "websiteUrl": "https://www.techinnovations.com",
    "numberOfEmployees": "MEDIUM",
    "otherDescription": "A leading coffee company in technology and software development."
}

--boundary
Content-Disposition: form-data; name="logo"; filename="blogone.png"
Content-Type: image/png

@ ./public/blogone.png
--boundary--